[book]
title = "PersiaML Tutorials"
description = "Guide on how to use PersiaML, a large scale sparse model training framework"
author = "Kuaishou AI Platform <admin@mail.xrlian.com>"

[preprocessor.open-git-repo]
command = "mdbook-open-on-gh"
renderer = ["html"]

[preprocessor.katex]

# [output.linkcheck]

[output.html]
follow-web-links = true
traverse-parent-directories = false
warning-policy = "error"
git-repository-url = "https://github.com/PersiaML/tutorials"
additional-css = ["open-in.css"]
